services:
  web:
    build: ./php
    ports:
      - "8080:80"
    volumes:
      - ./php/www:/var/www/html
    depends_on:
      - db
    environment:
      DB_NAME: gestion_produits
      DB_USER: user
      DB_PASS: pass
    container_name: php-eval-kube

  db:
    build: ./database
#pour prod    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: gestion_produits
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: php-db

volumes:
  mysql_data:

