version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_NAME: gestion_produits
      DB_USER: user
      DB_PASS: pass
    container_name: php-eval-kube

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_produits
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/gestion_produits.sql
    container_name: php-db

volumes:
  mysql_data:

